New Emailer class realization
torrentpier/torrentpier pull request #537
Opened 2023-02-19 10:58 UTC by belomaxorka

2023-02-19 23:17 UTC, Exileum requested changes
Нужно поправить ряд моментов.

2023-02-19 23:17 UTC, Exileum commented on admin/admin_mass_email.php
> -            $emailer->set_from([$bb_cfg['board_email'] => $bb_cfg['sitename']]);
Тут и далее - это указывалось чтобы письмо приходило от читаемого адресата, не просто какой-то email, а заголовок с названием отправителя - названием форума и т.п. Это достаточно стандартное для всех поведение, кажется что убирать это излишне или надо дать возможность где-то задать имя форума которое в рассылках фигурировать будет.

2023-02-19 23:17 UTC, Exileum commented on composer.json
> +    "psr/container": "1.0.0",
Почему эта версия? Даже в рамках первой версии полно других минорных.

2023-02-19 23:17 UTC, Exileum commented on composer.json
> +    "symfony/mailer": "4.*",
Зачем такие старые версии? Под текущую версию php в проекте 5 подошла бы.

2023-02-19 23:17 UTC, Exileum commented on library/config.php
> +    'dsn' => 'smtp://user:pass@smtp.example.com:25'
Для простого пользователя формат слишком сложный. Нужны примеры. Как было - конфигурировать проще, как минимум из-за наличия комментариев.

2023-02-19 23:17 UTC, Exileum commented on src/Emailer.php
> + * @link      https://github.com/TorrentPeer/TorrentPier for the canonical source repository
Ну не, копирайт то чем провинился.

2023-02-19 23:17 UTC, Exileum commented on src/Emailer.php
> -                /** @var Swift_SmtpTransport $transport local SMTP */
То что это пропало - плохо. У большинства все же локальный smtp и не обязательно заставлять их что-то вообще конфигурировать чтобы отсылать через него.

2023-02-19 23:17 UTC, Exileum commented on src/Emailer.php
> +        $charset = $bb_cfg['charset'];
Переменная не нужна, экономия на спичках.

2023-02-19 23:17 UTC, Exileum commented on src/Emailer.php
> +        $transport = Transport::fromDsn($bb_cfg['emailer']['dsn']);
Аналогично, если одно применение можно и без переменной, тем более что транспорт достаточно большой в плане памяти. Но я выше написал, скорее всего надо на локальном хосте другой транспорт автоматически подставлять.

2023-02-19 23:17 UTC, Exileum commented on src/Emailer.php
> +            {
Что за скобки? https://www.php.net/manual/en/control-structures.switch.php

Вообще не понимаю как это линтер пропустил.

2023-02-19 23:17 UTC, Exileum commented on src/Emailer.php
> +        /** проверка на успешную отправку */
В идеале бы комментарии на английском вести, как и основной язык движка.

2023-02-19 23:17 UTC, Exileum commented on styles/templates/admin/admin_forums.tpl
> -			&nbsp;&middot;&nbsp;
Вообще тут сделано было не просто так и названия были тоже даны такие не просто так. Когда форумов много с длинными локализациями страница слишком большая. Тем более я не уверен что у нас подобраны корректные языковые переменные.

2023-02-19 23:51 UTC, belomaxorka commented on composer.json
> +    "psr/container": "1.0.0",
Версии выше требуют более высокую версию php, у нас же минималка это 7.1.3. Поэтому и версии пакетов такие старые

2023-02-19 23:51 UTC, belomaxorka commented on composer.json
> +    "symfony/mailer": "4.*",
Аналогично как и выше

2023-02-19 23:53 UTC, belomaxorka commented on src/Emailer.php
> + * @link      https://github.com/TorrentPeer/TorrentPier for the canonical source repository
Банальная невнимательность 👉👈

2023-02-19 23:55 UTC, belomaxorka commented on src/Emailer.php
> +            {
Спецификацией не запрещено, а вообще, я не знаю почему давным давно так написал. 🚬

2023-02-19 23:56 UTC, belomaxorka commented on src/Emailer.php
> +        /** проверка на успешную отправку */
В движке много где русские комментарии замечал, надо в будущем переписать их на английский

2023-02-19 23:59 UTC, belomaxorka commented on styles/templates/admin/admin_forums.tpl
> -			&nbsp;&middot;&nbsp;
- Использовать сокращённые названия дабы не потерять в плане локализации.
- Тоже не уверен что подобраны корректные языковые переменные в принципе, но ключи DELETE и EDIT - в движке почти повсюду, лично в их корректности сомнений нет

2023-02-20 00:03 UTC, belomaxorka commented on composer.json
> +    "psr/container": "1.0.0",
Как оказалось у нас движок на данном этапе как раз таки лучше всего работает именно на версии PHP 7.1, поэтому использование старых версий пакетов оправданно, иначе были бы очень жёсткие рамки в плане версий. Фактически движок тогда был бы заточен только по одну версию php (либо 7.2, либо 7.3) на версиях выше нужно переписывать весь код, либо отключать нотисы. Так-то так

2023-02-20 00:05 UTC, belomaxorka commented on admin/admin_mass_email.php
> -            $emailer->set_from([$bb_cfg['board_email'] => $bb_cfg['sitename']]);
Symfony такой синтаксис не кушает, ему нужен именно адреса.

https://symfony.com/doc/current/mailer.html#email-addresses

2023-02-20 00:28 UTC, belomaxorka commented on composer.json
> +    "symfony/mailer": "4.*",
Компоненты симфони от версии 5.0 до 5.4 (актуальная из 5.* ветки) требуют версию php 7.2.5

2023-02-20 02:02 UTC, belomaxorka commented on library/config.php
> +    'dsn' => 'smtp://user:pass@smtp.example.com:25'
Да, тут стоило бы упростить, но в самом классе все равно придется приводить всё в dsn вид

2023-02-20 02:05 UTC, belomaxorka commented on src/Emailer.php
> +        $charset = $bb_cfg['charset'];
👌

2023-02-20 02:06 UTC, belomaxorka commented on src/Emailer.php
> +        $transport = Transport::fromDsn($bb_cfg['emailer']['dsn']);
👌

2023-02-20 08:45 UTC, closed without merging