Added nedeed "ORDER BY" in sql query
torrentpier/torrentpier pull request #557
Opened 2023-03-02 16:52 UTC by belomaxorka

Исправлена ошибка которая возникает в файле **admin/stats/tracker.php** (MySQL 8.0).

Лог:
```
#001064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC LIMIT 300' at line 1

SELECT COUNT(*) AS peers FROM tmp_tracker GROUP BY update_time DESC LIMIT 300

Source  : admin\stats\tracker.php(71) :: db.torrentpier
IP      : 127.0.0.1
Date    : 2023-03-02 19:01:18
Agent   : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Req_URI : /admin/stats/tracker.php
Referer : http://localhost/admin/index.php?pane=right
Method  : GET
```

https://dev.mysql.com/doc/refman/8.0/en/select.html
https://stackoverflow.com/questions/53846308/group-by-desc-syntax-error-on-mysql-8-0-which-is-fine-on-5-7

2023-03-02 18:13 UTC, JDVU commented
и опять же ошибка. начали с одинарной кавычки, а закончили двойной

2023-03-02 22:24 UTC, belomaxorka commented
> и опять же ошибка. начали с одинарной кавычки, а закончили двойной

Чисто фактически ошибки там нет. К тому же, переменную  $peers_in_last_sec_limit мы бы не смогли разместить в одинарных кавычках.

2023-03-03 01:31 UTC, Exileum requested changes

2023-03-03 01:31 UTC, Exileum commented on admin/stats/tracker.php
> +$rowset = DB()->fetch_rowset('SELECT COUNT(*) AS peers FROM ' . TMP_TRACKER_TABLE . ' GROUP BY update_time ORDER BY update_time DESC LIMIT' . " $peers_in_last_sec_limit");
После лимита надо пробел, иначе слитно конкатенирует. Ну и вообще не нужны двойные кавычки в конце.

2023-03-03 16:52 UTC, Exileum approved these changes

2023-03-03 16:52 UTC, merged